### ISSUE TITLE
it ain't work

### ISSUE THREAD

**Issue by joshsleeper** [dino-dna/clipster#1]
# problem
windows is like... nah.
![image](https://user-images.githubusercontent.com/849941/34546067-4e92fe4a-f0a6-11e7-8380-f5be8e4fc8b0.png)

# solution
ask it nicely? idk

**Comment by cdaringe** [comment]
You don't work, and it's your fault!! ;) jk thx

**Comment by cdaringe** [comment]
fixed in 5171f63
